image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  services:
    - node:latest
  script:
    - npm run test:docker

deploy:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_CI_API_KEY
  only:
    - master