version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: hybot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: hybot
      MYSQL_DATABASE: hybotdb
      MYSQL_USER: hybot
      MYSQL_PASSWORD: hybot
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - mysql_hybot_net

  hybot:
    image: node
    container_name: hybot-node
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - '3000:3000'
      - '9229:9229' # debug port of Node apps.
    networks:
      - mysql_hybot_net
    links:
      - mysql:mysql
    build:
      context: .
      dockerfile: Dockerfile-test

networks:
  mysql_hybot_net:
    driver: bridge
